# vim:fileencoding=utf-8:foldmethod=marker

#: Cursor customization {{{

cursor #ff00ff

#: Default cursor color. If set to the special value none the cursor
#: will be rendered with a "reverse video" effect.

# cursor_text_color #111111

#: The color of text under the cursor.

# cursor_shape block

#: The cursor shape can be one of block, beam, underline.

# cursor_beam_thickness 1.5

# cursor_underline_thickness 2.0

# cursor_blink_interval -1

# cursor_stop_blinking_after 15.0

#: }}}

#: Scrollback {{{

# scrollback_lines 2000

#: Number of lines of history to keep in memory for scrolling back.

# scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER

# scrollback_pager_history_size 0

# scrollback_fill_enlarged_window no

# wheel_scroll_multiplier 5.0

# wheel_scroll_min_lines 1

# touch_scroll_multiplier 1.0

#: }}}

#: Mouse {{{

# mouse_hide_wait 3.0

# url_color #0087bd
# url_style curly

# open_url_with default

# url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh

# detect_urls yes

# url_excluded_characters

# show_hyperlink_targets no

# copy_on_select no

# paste_actions quote-urls-at-prompt

# strip_trailing_spaces never

# select_by_word_characters @-./_~?&=%+#

# click_interval -1.0

# focus_follows_mouse no

# pointer_shape_when_grabbed arrow

# default_pointer_shape beam

# pointer_shape_when_dragging beam

#: }}}

#: Performance tuning {{{

# repaint_delay 10

# input_delay 3

# sync_to_monitor yes

#: }}}

#: Terminal bell {{{

# enable_audio_bell yes

# visual_bell_duration 0.0

# visual_bell_color none

# window_alert_on_bell yes

# bell_on_tab "🔔 "

# command_on_bell none

# bell_path none

#: }}}

#: Color scheme {{{

# foreground #dddddd
# background #000000

#: The foreground and background colors.

background_opacity 0.8

#: The opacity of the background. A number between zero and one, where
#: one is opaque and zero is fully transparent. This will only work if
#: supported by the OS (for instance, when using a compositor under X11).

# Note: Update this path for Linux instead of macOS
# background_image ~/Pictures/wallpapers/night_desert.png
# background_image ~/Pictures/wallpapers/sean-sinclair.png
# background_image ~/Pictures/wallpapers/leaves1.png
# background_image ~/Pictures/wallpapers/leaves3.png

#: Path to a background image. Must be in PNG format.

background_image_layout scaled

#: Whether to tile, scale or clamp the background image.
#: Can be one of: tiled, mirror-tiled, scaled, clamped, centered.

# background_image_linear no

# dynamic_background_opacity no

background_tint 0.8

#: How much to tint the background image by the background color.

background_tint_gaps -10.0

#: How much to tint the background image at the window gaps.

# dim_opacity 0.75

# selection_foreground #000000
# selection_background #fffacd

#: The foreground and background colors for text selected with the mouse.

#: }}}

#: Advanced {{{

# shell .

#: The shell program to execute. The default value of . means to use
#: whatever shell is set as the default shell for the current user.

editor /usr/bin/hx

#: The terminal based text editor to use when editing the kitty config file.

# close_on_child_death no

# allow_remote_control no

# listen_on none

# env

# update_check_interval 24

# clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask

# clipboard_max_size 512

# file_transfer_confirmation_bypass

# allow_hyperlinks yes

# shell_integration enabled

# allow_cloning ask

# clone_source_strategies venv,conda,env_var,path

# term xterm-kitty

#: }}}

#: OS specific tweaks {{{

# wayland_titlebar_color system

# linux_display_server auto

#: Choose between Wayland and X11 backends. By default, an appropriate
#: backend based on the system state is chosen automatically.

#: }}}
