shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["*.zsh"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
use = ["*.zsh"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
use = ["*.zsh"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
use = ["*.zsh"]
