#: Catppuccin Mocha Theme

foreground            #cdd6f4
background            #1e1e2e
selection_foreground  #1e1e2e
selection_background  #f5e0dc

#: Grayscale
color0                #45475a
color8                #545862

#: Red
color1                #f38ba8
color9                #e06c75

#: Green
color2                #a6e3a1
color10               #98c379

#: Yellow
color3                #f9e2af
color11               #e5c07b

#: Blue
color4                #89b4fa
color12               #61afef

#: Magenta
color5                #f5c2e7
color13               #c678dd

#: Cyan
color6                #94e2d5
color14               #56b6c2

#: White
color7                #bac2de
color15               #c8ccd4
