#!/bin/bash
# Cron scheduling module

# Function to setup cron job
setup_cron() {
    if [ "$ENABLE_AUTO_BACKUP" = false ]; then
        log_message "WARNING" "Auto backup is disabled in configuration"
        return 0
    fi
    
    local cron_time=""
    
    # Convert backup time to cron format
    local hour=$(echo "$BACKUP_TIME" | cut -d: -f1)
    local minute=$(echo "$BACKUP_TIME" | cut -d: -f2)
    
    case "$BACKUP_FREQUENCY" in
        "daily")
            cron_time="$minute $hour * * *"
            ;;
        "weekly")
            cron_time="$minute $hour * * 0"  # Sunday
            ;;
        "monthly")
            cron_time="$minute $hour 1 * *"
            ;;
        *)
            log_message "ERROR" "Unknown backup frequency: $BACKUP_FREQUENCY"
            return 1
            ;;
    esac
    
    local cron_job="$cron_time root /usr/local/bin/backit >> $LOG_DIRECTORY/cron.log 2>&1"
    
    # Create cron.d file
    local cron_file="/etc/cron.d/backit"
    
    echo "# Auto-generated by backit setup" > "$cron_file"
    echo "# Backup frequency: $BACKUP_FREQUENCY at $BACKUP_TIME" >> "$cron_file"
    echo "$cron_job" >> "$cron_file"
    
    log_message "INFO" "Cron job created in $cron_file"
    log_message "INFO" "Schedule: $cron_job"
    
    # Restart cron service
    if systemctl restart cron 2>/dev/null || service cron restart 2>/dev/null; then
        log_message "INFO" "Cron service restarted"
    else
        log_message "WARNING" "Could not restart cron service, but job was created"
    fi
    
    return 0
}

# Function to remove cron job
remove_cron() {
    local cron_file="/etc/cron.d/backit"
    
    if [ -f "$cron_file" ]; then
        rm -f "$cron_file"
        log_message "INFO" "Cron job removed: $cron_file"
        
        # Restart cron service
        if systemctl restart cron 2>/dev/null || service cron restart 2>/dev/null; then
            log_message "INFO" "Cron service restarted"
        fi
    else
        log_message "INFO" "No cron job found to remove"
    fi
    
    return 0
}
