# vim:fileencoding=utf-8:foldmethod=marker

#: Window layout {{{

# remember_window_size  yes
# initial_window_width  640
# initial_window_height 400

#: If enabled, the OS Window size will be remembered so that new
#: instances of kitty will have the same size as the previous instance.

# Three columns: Two full-size (33% of screen each), and one that splits vertically.
enabled_layouts tall:bias=66;full_size=2;mirrored=true,splits

#: The enabled window layouts. A comma separated list of layout names.
#: The first listed layout will be used as the startup layout.

# window_resize_step_cells 2
# window_resize_step_lines 2

#: The step size to use when resizing kitty windows in a layout

window_border_width 1pt

#: The width of window borders. Borders are displayed only when more 
#: than one window is visible.

draw_minimal_borders no

#: Draw only the minimum borders needed. This means that only the
#: borders that separate the window from a neighbor are drawn.

window_margin_width 10

#: The window margin (in pts) (blank area outside the border).

single_window_margin_width 0

#: The window margin to use when only a single window is visible.

window_padding_width 0

#: The window padding (in pts) (blank area between the text and the window border).

# placement_strategy center

#: When the window size is not an exact multiple of the cell size,
#: control how the padding is distributed.

active_border_color #44ffff

#: The color for the border of the active window.

# inactive_border_color #00ff

#: The color for the border of inactive windows.

# bell_border_color #ff5a00

#: The color for the border of inactive windows in which a bell has occurred.

# inactive_text_alpha 1.0

#: Fade the text in inactive windows by the specified amount.

#: }}}

#: Tab bar {{{

# tab_bar_edge bottom

tab_bar_style powerline

#: The tab bar style, can be one of: fade, slant, separator, powerline, custom, hidden

# tab_bar_align left

# tab_bar_min_tabs 2

# tab_switch_strategy previous

tab_powerline_style slanted

#: The powerline separator style between tabs when using powerline style.
#: Can be one of: angled, slanted, round.

# tab_activity_symbol none

# tab_title_max_length 0

# tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}"

# active_tab_title_template none

# active_tab_foreground   #000
# active_tab_background   #eee
active_tab_font_style   bold
# inactive_tab_foreground #444
# inactive_tab_background #999
# inactive_tab_font_style normal

#: Tab bar colors and styles.

# tab_bar_background none

# tab_bar_margin_color none

#: }}}
